### ISSUE TITLE
Use SSR

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#13]
There's been some additional discussion of using SSR in place of CSR for the deployment.  This would allow us to leverage ELB/NLB.  It's also analogous to the approach Aura is taking.  The downside is that it's a less proven architecture and might expose us to bugs.

**Comment by benofben** [comment]
Ed confirmed SSR is going to be default in 5.0.  We should make this switch ASAP.

**Comment by edrandall-dev** [comment]
A revision to the AWS marketplace CF template is under active development. It will enable users to select SSR as an option which will provision a network load balancer and make the necessary neo4j.conf changes.

**Comment by edrandall-dev** [comment]
CSR has been removed as an option, as requested by Ben.  SSR is now the default, and network infrastructure (including a Network Load Balancer) is provisioned accordingly.

**Comment by edrandall-dev** [comment]
Closing Issue.
