### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#17]

**Comment by harshitsinghvi22** [comment]
https://github.com/neo-technology/neo4j-manual-modeling/pull/2945
https://github.com/neo-technology/neo4j-manual-modeling/pull/2930

The above PR fixes the title and the documentation

https://neo4j.com/docs/operations-manual/4.4/cloud-deployments/cloudVms/ --> This  page will be removed too.
