### ISSUE TITLE
Remove Key

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#25]
Confirmed that 22 needs to be open via both testing and documentation.

"Ensure that the security group associated with your instance [allows inbound SSH traffic](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html#add-rule-authorize-access) on port 22 from your IP address or from your network. The default security group for the VPC does not allow incoming SSH traffic by default. The security group created by the launch wizard allows incoming SSH traffic by default. For more information, see [Authorize inbound traffic for your Linux instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html)."

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html?icmpid=docs_ec2_console#ec2-instance-connect-setup-security-group

This "solution" looks worse than the problem.  https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html

Wondering if there's some value we could put for the CIDR where connectivity would work and the CIDR wouldn't need to be exposed as a parameter.

Regardless, I think we can drop the keypair requirement.

**Comment by edrandall-dev** [comment]
Keypair requirement (and parameter) has been removed and tested.  Connectivity still works via EC2 instance connect.  Expectation will need to be set with all marketplace users that this is the only way to connect via ssh.

Issue to remain open until merge to main.

**Comment by edrandall-dev** [comment]
https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/pull/26

**Comment by edrandall-dev** [comment]
Key removal merged to main.

**Comment by edrandall-dev** [comment]
"Wondering if there's some value we could put for the CIDR where connectivity would work and the CIDR wouldn't need to be exposed as a parameter." - I suspect we can effect this in CloudFormation without issue, but will it pass the AWS validation upon submission?
