### ISSUE TITLE
Add t3.2xl to allowed instances

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#29]
I think a little more headroom in the t3 class would be good.  I'm trying an r6 in our perf issue to see if it goes away.

I do think keeping the allowed types somewhat constrained is useful to encourage people to go down a well trod happy path.

**Comment by edrandall-dev** [comment]
Completed. PR Merged.

**Comment by harshitsinghvi22** [comment]
https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/commit/e63acdbfe52799264ea5964c706c82b5184e2fc9
https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/commit/e7348327d5edf90975f9b51076ed8d831b32e317
