### ISSUE TITLE
Investigate impact of reboot and cloud init interaction

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#32]
I think the cloud init script might re run on reboot.  Not sure what that would do.  It'd be good to understand the impact here.  We're going to see more of these as we do more operational work.

**Comment by edrandall-dev** [comment]
Running on reboot (in addition to first boot) is NOT the default behaviour, however this can be changed if required.

[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts]

**Comment by benofben** [comment]
We would not want it to run.  If it doesn’t I think we’re all good.  I just had this feeling that it might but I can’t remember where I last observed that.

**Comment by harshitsinghvi22** [comment]
Enabled systemctl neo4j since on reboot neo4j was not coming up
https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/commit/d2d34daa8bdcb1e324e88583e0403e0337e11e51
