### ISSUE TITLE
Look through debug.log

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#36]
There's a whole bunch of "failed library load" etc stuff in there.  Not sure what's happening but it doesn't look like a clean start.

**Comment by harshitsinghvi22** [comment]
Raised the below issue with apoc dev team...they are taking a look at it
https://trello.com/c/WowRDYkU/240-apoc-warnings-seen-on-neo4j-449-enterprise-startup-using-apoc-core-4406-jar

**Comment by harshitsinghvi22** [comment]
As per some comments from dev team , they are working on removing some of the warnings and its expected for now (aws ,s3 warnings) , for others investigation is in progress

**Comment by edrandall-dev** [comment]
Closing issue as trello card raised and now with correct team.
