### ISSUE TITLE
I suspect we're not using the LB for database traffic.

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#37]
See this line:             
`sed -i s/#dbms.default_advertised_address=localhost/dbms.default_advertised_address=${publicHostname}/g /etc/neo4j/neo4j.conf\n"
`

That means that the node is returning this as the place for nodes to connect to.  This probably ought to be configured to be the LB address.

I bet this is why you need the security groups for things to work.

**Comment by harshitsinghvi22** [comment]
This is fixed as part of the read replica PR
