### ISSUE TITLE
Improve License message

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#38]
" (License keys will be sent to and stored by Neo4j. This information will only be used for the purposes of product activation.)"

I'm not sure what this message is trying to get across.  I'd suggest removing it.

**Comment by harshitsinghvi22** [comment]
this was a request from the aws marketplace team to mention the details as per the below document
https://docs.aws.amazon.com/marketplace/latest/userguide/product-and-ami-policies.html#customer-information

**Comment by harshitsinghvi22** [comment]
I dont think we can remove it @benofben ....removing it will lead to adding the same from the AWS team

**Comment by edrandall-dev** [comment]
Closing Issue.  As @harshitsinghvi22 has stated, this was a request direct from the AWS MP team.
