### ISSUE TITLE
Remove Subnet CIDR Block

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#39]
Looks like the CIDR block is optional.  Assuming so, we don't need to be opinionated about this and can let the platform chose a default.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-cidrblock

**Comment by harshitsinghvi22** [comment]
![Screenshot 2022-07-28 at 10 32 55](https://user-images.githubusercontent.com/89837129/181473165-83882ba8-85a0-4f4c-8b5e-0225db12483c.png)


Not possible !! AWS does not allow you to create subnet without CIDR block

Could be a documentation error as the documentation says

**When you create each subnet, you provide the VPC ID and IPv4 CIDR block for the subnet. After you create a subnet, you can’t change its CIDR block. The size of the subnet’s IPv4 CIDR block can be the same as a VPC’s IPv4 CIDR block, or a subset of a VPC’s IPv4 CIDR block. If you create more than one subnet in a VPC, the subnets’ CIDR blocks must not overlap. The smallest IPv4 subnet (and VPC) you can create uses a /28 netmask (16 IPv4 addresses), and the largest uses a /16 netmask (65,536 IPv4 addresses).**
