### ISSUE TITLE
change bolt:// to neo4j://

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#45]
https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/blob/52e0c4e02868539bfcb53d664fb74fe3136729ae/marketplace/neo4j.template.yaml#L796

neo4j seems to be a more general way to state this.

**Comment by harshitsinghvi22** [comment]
https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/pull/47
