### ISSUE TITLE
update simple template

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#50]
We seem to have let this fall behind the MP template.  We need to update it now and then keep it up to date going forward.

**Comment by benofben** [comment]
Harshit has suggested maybe we get rid of simple.  In that case we need to make sure the marketplace template is easily consumable via GitHub (console and CLI).

**Comment by edrandall-dev** [comment]
clean up properly and enhance documentation

**Comment by edrandall-dev** [comment]
This is done.  Simple has been removed and documentation has been improved for the marketplace template.
