### ISSUE TITLE
Regex for license keys

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#52]

**Comment by benofben** [comment]
The two periods would help somewhat.

One issue we encountered was lab attendees who fat fingered appending the correct license key to the default value of "None" in the field.  So, that would have passed the proposed regex but still failed for the attenedees.  

I'd suggest something like (it's been a while since I regularly wrote Perl...):

None || [0-9a-zA-Z].[0-9a-zA-Z].[0-9a-zA-Z]{however many characters a license key is}

I think if we got the general form plus the length, that'd eliminate 99% of the issues.

**Comment by benofben** [comment]
There is no fixed length.  So what I proposed above wouldn't work.

**Comment by edrandall-dev** [comment]
This idea was discussed but abandoned
