### ISSUE TITLE
add apoc.* unrestricted

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#6]
- "sed -i s/#dbms.security.procedures.unrestricted=my.extensions.example,my.procedures.*/dbms.security.procedures.unrestricted=gds.*,bloom.*/g /etc/neo4j/neo4j.conf\n"

**Comment by harshitsinghvi22** [comment]
This is fixed with PR https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/pull/7
