### ISSUE TITLE
Add Private Only Template

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/amazon-cloud-formation-neo4j#63]
Add a private IP,subnet, etc only template to this GitHub repo.  Note we don't want to list that in Marketplace due to usability issues.

**Comment by drumcircle** [comment]
Strongly disagree with sentiment that private IP alone qualifies this as a separate template or that it should not be in marketplace.  Private ought to be one of many configuration options that provide flexibility and which avoid customers having to roll their own, which is what happens today.

**Comment by edrandall-dev** [comment]
This has now been completed and is available at:

https://github.com/neo4j-partners/amazon-cloud-formation-neo4j)/custom-templates/

We are unlikely to attempt to roll this feature into the main marketplace template but plan on producing other custom templates in the same location as the need arises.
